server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    absolute_redirect off;

    error_page 404 /404.html;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://github.com https://release-assets.githubusercontent.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;" always;
    add_header Strict-Transport-Security "max-age=31536000" always;

    location /.well-known/security.txt {
        return 302 https://www.ncsc.nl/.well-known/security.txt;
    }

    location / {
        if (-d $request_filename) {
            rewrite ^(.+[^/])$ $1/ permanent;
        }
        try_files $uri $uri/ =404;
    }
}
