# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
        exclude: mkdocs.yml
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
        - id: ruff
        - id: ruff-format
# Lokale hooks voor Algoritmekader validaties
-   repo: local
    hooks:
    -   id: algoritmekader-validaties
        name: Algoritmekader validaties
        description: Voert alle validatiescripts uit voor het Algoritmekader
        entry: python script/validation/run_all_validations.py
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies: [pyyaml]

ci:
  autofix_prs: false
  autofix_commit_msg: "Auto fix pre-commit.com hooks"
  autoupdate_commit_msg: "Update .pre-commit-config.yaml"
