name: Algoritmekader URN en Levenscyclus Validatie

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/voldoen-aan-wetten-en-regels/maatregelen/**'
      - 'docs/voldoen-aan-wetten-en-regels/vereisten/**'
  push:
    branches: [ main ]
    paths:
      - 'docs/voldoen-aan-wetten-en-regels/maatregelen/**'
      - 'docs/voldoen-aan-wetten-en-regels/vereisten/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Validate URN uniqueness
        run: python .github/scripts/validate_urn_uniqueness.py

      - name: Validate lifecycles
        run: python .github/scripts/validate_all_labels.py

      - name: Validate file prefix and URN consistency
        run: python .github/scripts/validate_file_prefix_urn.py
